apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-deployment
  labels:
    deployment: animals
    type: green

spec:
  selector:
    matchLabels:
      app: animal
  replicas: 2
  template:
    metadata:
      labels:
        app: animal
    spec:
     containers:
     - name: moose
       image: supergiantkir/animals:moose
       ports:
       - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deployment
  labels:
     type: blue
     deployment: animals
spec:
  selector:
    matchLabels:
      app: animal
  replicas: 2
  template:
    metadata:
      labels:
        app: animal
    spec:
     containers:
