apiVersion: v1
kind: Pod
metadata:
  name: volumeEx
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: volume1
      mountPath: /storage
  - name: app2
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: volume1
      mountPath: /storage
  volumes:
  - name: volume1
    emptyDir: {}
