kind: Service     
apiVersion: v1
metadata:
  name: spring-service
spec:
  selector:
    app: spring   
  ports:         
  - name: http   
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
