kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: springMusic # Name of the service
spec:
  selector:
    app: exposeservice    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: http    # Setting multiple ports listterns 
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9388
type: LoadBalancer
